# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qV4xneoVNwdnmGiSbepVILGCGjf66GA-
"""

import torch.cuda

DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"
DEVICE



